### ISSUE TITLE
unsuscribe failed - Internal server error

### ISSUE THREAD

**Issue by nykoo** [TychoTheTaco/Twitch-Drops-Notifier#6]
Hi,

First of all, thank you for this usefull tool :)

i tried to unsuscribed a  mail i don"t use anymore and i have this error :

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

just to let you know ;)

**Comment by TychoTheTaco** [comment]
Hi, Thanks for letting me know. If you want, you can DM me the email and I'll manually remove it.
