### ISSUE TITLE
Able to Include Item for Drop?

### ISSUE THREAD

**Issue by BlueCrew86** [TychoTheTaco/Twitch-Drops-Notifier#9]
Absolutely love this - only configuration I was curious about was if there was any way to include the Reward / Item that is in the drop with the notification?

**Comment by TychoTheTaco** [comment]
This used to be included with the notification, but Twitch added some bot prevention mechanism a while back which makes it difficult to get those details now and I didn't want to spend any more time trying to work around it.

**Comment by BlueCrew86** [comment]
Gotta love it when they actively put things in place to prevent functionality. -_-

**Comment by BlueCrew86** [comment]
LOVE THE UPDATE!!
